export const OUTBOX_TYPES = {
  LEDGER_PAYIN_CREDIT: "LEDGER_PAYIN_CREDIT",
  LEDGER_PAYOUT_COMMIT: "LEDGER_PAYOUT_COMMIT",
  LEDGER_PAYOUT_VOID: "LEDGER_PAYOUT_VOID",
  MERCHANT_CALLBACK: "MERCHANT_CALLBACK",
} as const;

export type OutboxType = (typeof OUTBOX_TYPES)[keyof typeof OUTBOX_TYPES];
