export const RESILIENCE_DEFAULTS = {
  PROVIDER_TIMEOUT_MS: 10000,
  PROVIDER_RETRIES: 2,
  PROVIDER_RETRY_BASE_MS: 300,
  PROVIDER_RETRY_MAX_MS: 3000,
  PROVIDER_RETRY_JITTER: 0.2,
  CIRCUIT_FAILURE_THRESHOLD: 5,
  CIRCUIT_OPEN_MS: 30000,
};

export const WEBHOOK_RETRY_DEFAULTS = {
  MAX_ATTEMPTS: 5,
  BASE_DELAY_MS: 1000,
  MAX_DELAY_MS: 30000,
};
