export enum TransactionType {
    // Standard Types
    PAYIN = "PAYIN",
    PAYOUT = "PAYOUT",
    INTERNAL_TRANSFER = "INTERNAL_TRANSFER",

    // Operation Types (Harmonized)
    MERCHANT_SETTLEMENT = "MERCHANT_SETTLEMENT",
    MERCHANT_PAYOUT_FUND = "MERCHANT_PAYOUT_FUND",
    MERCHANT_DEDUCT = "MERCHANT_DEDUCT",
    MERCHANT_FEES = "MERCHANT_FEES",
    MERCHANT_REFUND = "MERCHANT_REFUND",
    MERCHANT_HOLD = "MERCHANT_HOLD",
    MERCHANT_RELEASE = "MERCHANT_RELEASE",

    PROVIDER_SETTLEMENT = "PROVIDER_SETTLEMENT",
    PROVIDER_TOPUP = "PROVIDER_TOPUP",
    PROVIDER_FEES = "PROVIDER_FEES",
    PROVIDER_FEES_SETTLE = "PROVIDER_FEES_SETTLE",

    LE_INCOME_SETTLE = "LE_INCOME_SETTLE",
}

export enum TransactionEntityType {
    MERCHANT = "MERCHANT",
    PROVIDER_LEGAL_ENTITY = "PROVIDER_LEGAL_ENTITY",
    LEGAL_ENTITY = "LEGAL_ENTITY",
    SYSTEM = "SYSTEM",
    SUPER_ADMIN = "SUPER_ADMIN",
    WORLD = "WORLD",
}

export enum TransactionPartyType {
    CUSTOMER = "CUSTOMER",
    BENEFICIARY = "BENEFICIARY",
    OTHER = "OTHER",
    SELF = "SELF",
}
