export enum TransactionType {
    // Standard Types
    PAYIN = "PAYIN",
    PAYOUT = "PAYOUT",
    INTERNAL_TRANSFER = "INTERNAL_TRANSFER",

    // Operation Types (Harmonized)
    MERCHANT_SETTLEMENT = "MERCHANT_SETTLEMENT",
    MERCHANT_BANK_SETTLEMENT = "MERCHANT_BANK_SETTLEMENT",
    MERCHANT_DEPOSIT = "MERCHANT_DEPOSIT",
    MERCHANT_PAYOUT_FUND = "MERCHANT_PAYOUT_FUND",
    MERCHANT_DEDUCT = "MERCHANT_DEDUCT",
    MERCHANT_FEES = "MERCHANT_FEES",
    MERCHANT_REFUND = "MERCHANT_REFUND",
    MERCHANT_HOLD = "MERCHANT_HOLD",
    MERCHANT_RELEASE = "MERCHANT_RELEASE",
    MERCHANT_WITHDRAWAL = "MERCHANT_WITHDRAWAL",
    MERCHANT_INCOME_SETTLEMENT = "MERCHANT_INCOME_SETTLEMENT",

    PROVIDER_SETTLEMENT = "PROVIDER_SETTLEMENT",
    PROVIDER_TOPUP = "PROVIDER_TOPUP",
    PROVIDER_DEPOSIT = "PROVIDER_DEPOSIT",
    PROVIDER_FEES = "PROVIDER_FEES",
    PROVIDER_FEES_SETTLE = "PROVIDER_FEES_SETTLE",

    LE_INCOME_SETTLE = "LE_INCOME_SETTLE",
    LEGAL_ENTITY_SETTLEMENT = "LEGAL_ENTITY_SETTLEMENT",
    LEGAL_ENTITY_DEPOSIT = "LEGAL_ENTITY_DEPOSIT",
    LEGAL_ENTITY_DEDUCT = "LEGAL_ENTITY_DEDUCT",
    PLE_SETTLEMENT = "PLE_SETTLEMENT",
    PLE_DEPOSIT = "PLE_DEPOSIT",
    PLE_EXPENSE_SETTLEMENT = "PLE_EXPENSE_SETTLEMENT",
    PLE_EXPENSE_CHARGE = "PLE_EXPENSE_CHARGE",
}

export enum TransactionPartyType {
    CUSTOMER = "CUSTOMER",
    BENEFICIARY = "BENEFICIARY",
    MERCHANT = "MERCHANT",
    PROVIDER_LEGAL_ENTITY = "PROVIDER_LEGAL_ENTITY",
    LEGAL_ENTITY = "LEGAL_ENTITY",
    SYSTEM = "SYSTEM",
    SUPER_ADMIN = "SUPER_ADMIN",
    WORLD = "WORLD",
    OTHER = "OTHER",
}

// Risk / compliance flags for transactions
export enum TransactionFlag {
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH",
    MANUAL_REVIEW = "MANUAL_REVIEW",
    SUSPICIOUS_IP = "SUSPICIOUS_IP",
    SIGNATURE_MISMATCH = "SIGNATURE_MISMATCH",
    ALTERED_REQUEST = "ALTERED_REQUEST",
    HIGH_VELOCITY = "HIGH_VELOCITY",
    DUPLICATE_DEVICE = "DUPLICATE_DEVICE",
    NAME_MISMATCH = "NAME_MISMATCH",
    ACCOUNT_MISMATCH = "ACCOUNT_MISMATCH",
    BENEFICIARY_BLACKLIST = "BENEFICIARY_BLACKLIST",
    CUSTOMER_BLACKLIST = "CUSTOMER_BLACKLIST",
    SANCTION_HIT = "SANCTION_HIT",
    CHARGEBACK_RISK = "CHARGEBACK_RISK",
    FRAUD_SUSPECTED = "FRAUD_SUSPECTED",
}
